# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "47484d5df9d437f794cb628c9577a979"
name = "checkout-shipping-custom"
handle = "checkout-shipping-custom"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "mih-dev-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping,write_shipping"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
